# Generated by Django 4.1.4 on 2023-01-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
