# Generated by Django 4.1.4 on 2023-01-21 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adopt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='AdopImages'),
            preserve_default=False,
        ),
    ]
