# Generated by Django 4.1.4 on 2023-01-26 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adopt', '0003_animal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='height',
            field=models.FloatField(blank=True, default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccines',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
