# Generated by Django 4.1.4 on 2023-01-29 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adopt', '0005_personinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='kind',
        ),
        migrations.AlterField(
            model_name='kindofpet',
            name='kind',
            field=models.CharField(max_length=50, verbose_name='Kind of Pet'),
        ),
        migrations.AlterField(
            model_name='personinformation',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='Adopt.kindofpet'),
            preserve_default=False,
        ),
    ]
