# Generated by Django 4.1.4 on 2023-01-30 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adopt', '0006_remove_animal_kind_alter_kindofpet_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinformation',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
