# Generated by Django 4.1.4 on 2023-02-09 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adopt', '0007_personinformation_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinformation',
            name='postal_code',
        ),
    ]
