# Generated by Django 4.1.4 on 2023-02-08 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
